title: JKAN (Demo)
description: "A delightfully simple way to find data from your city."
baseurl: /jkan
headerimage: /jkan/img/background.jpg

# Authentication
github_client_id: "4495b786ebf48fa5b007"
gatekeeper_host: http://sac-jkan-gate.herokuapp.com

# Categories
category_list:
  - Arts / Culture / History
  - Budget / Finance
  - Economy
  - Education
  - Elections / Politics
  - Environment
  - Food
  - Health / Human Services
  - Parks / Recreation
  - Planning / Zoning
  - Public Safety
  - Real Estate / Land Records
  - Transportation
  - Uncategorized
  
categories_images:
  Arts / Culture / History: "/img/portfolio/music.jpg"
  Budget / Finance: "/img/portfolio/calculator.jpg"
  Economy: "/img/portfolio/portfolio_03.jpg"
  Education: "/img/portfolio/computer.jpg"
  Elections / Politics: "/img/portfolio/portfolio_05.jpg"
  Environment: "/jkan/img/portfolio/leaf.jpg"
  Food: "/img/portfolio/food.jpg"
  Health / Human Services: "/img/portfolio/portfolio_08.jpg"
  Parks / Recreation: "/img/portfolio/portfolio_09.jpg"
  Planning / Zoning: "/img/portfolio/oneway.jpg"
  Public Safety: "/img/portfolio/portfolio_06.jpg"
  Real Estate / Land Records: "/img/portfolio/portfolio_03.jpg"
  Transportation: "/img/portfolio/bike.jpg"
  Uncategorized: "/img/portfolio/portfolio_05.jpg"

# Link for the "fork me on github" banner. Remove this line to suppress banner.
fork_me_url: https://github.com/sacmoei/jkan

# Nav bar
navigation:
  - title: Datasets
    url: /datasets/

# Collections
collections:
  datasets:
    output: true
    permalink: /datasets/:path/
  organizations:
    output: false

# Collections (cont'd)
defaults:
  - scope:
      path: ""
      type: datasets
    values:
      layout: dataset
      category: Uncategorized
      organization: N/A

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Exclude these files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .travis.yml
  - node_modules
  - scripts/src
  - package.json
  - webpack.config.js
  - README.md
  - LICENSE
